/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ComponentsRouteImport } from "./routes/components";
import { Route as ComponentsSlugRouteImport } from "./routes/components.$slug";
import { Route as ComponentsIndexRouteImport } from "./routes/components.index";
import { Route as IndexRouteImport } from "./routes/index";

const ComponentsRoute = ComponentsRouteImport.update({
  id: "/components",
  path: "/components",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ComponentsRoute,
} as any);
const ComponentsSlugRoute = ComponentsSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => ComponentsRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/components": typeof ComponentsRouteWithChildren;
  "/components/$slug": typeof ComponentsSlugRoute;
  "/components/": typeof ComponentsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/components/$slug": typeof ComponentsSlugRoute;
  "/components": typeof ComponentsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/components": typeof ComponentsRouteWithChildren;
  "/components/$slug": typeof ComponentsSlugRoute;
  "/components/": typeof ComponentsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/components" | "/components/$slug" | "/components/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/components/$slug" | "/components";
  id: "__root__" | "/" | "/components" | "/components/$slug" | "/components/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ComponentsRoute: typeof ComponentsRouteWithChildren;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/components": {
      id: "/components";
      path: "/components";
      fullPath: "/components";
      preLoaderRoute: typeof ComponentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/components/": {
      id: "/components/";
      path: "/";
      fullPath: "/components/";
      preLoaderRoute: typeof ComponentsIndexRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
    "/components/$slug": {
      id: "/components/$slug";
      path: "/$slug";
      fullPath: "/components/$slug";
      preLoaderRoute: typeof ComponentsSlugRouteImport;
      parentRoute: typeof ComponentsRoute;
    };
  }
}

interface ComponentsRouteChildren {
  ComponentsSlugRoute: typeof ComponentsSlugRoute;
  ComponentsIndexRoute: typeof ComponentsIndexRoute;
}

const ComponentsRouteChildren: ComponentsRouteChildren = {
  ComponentsSlugRoute: ComponentsSlugRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
};

const ComponentsRouteWithChildren = ComponentsRoute._addFileChildren(ComponentsRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsRoute: ComponentsRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";

import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
